name: temporal_gfn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.20.0
  - pandas>=1.3.0
  - pytorch>=1.10.0
  - torchvision
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - scikit-learn>=1.0.0
  - pyyaml>=6.0
  - tensorboard>=2.7.0
  - tqdm>=4.62.0
  - pytest>=6.2.5
  - pip>=21.0.0
  - pip:
      - hydra-core>=1.1.0
      - omegaconf>=2.1.0
      - wandb>=0.15.0
