# Synthetic dataset configuration

type: synthetic
context_length: 96
prediction_horizon: 24
scaler_type: mean
stride: 1
sample_stride: 5
return_indices: false

# Synthetic dataset parameters
num_series: 100
series_length: 200
model_type: combined
model_params:
  phi: 0.9
  period: 20
  amplitude: 1.0
  slope: 0.01
noise_level: 0.1
